#!/usr/bin/env python3
"""Configure runtime env file for OpenClaw ops scripts."""

from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

UTC = timezone.utc


def now_iso() -> str:
    return datetime.now(tz=UTC).replace(microsecond=0).isoformat()


def mask_value(value: str) -> str:
    text = str(value or "")
    if len(text) <= 8:
        return "*" * len(text)
    return text[:4] + ("*" * (len(text) - 8)) + text[-4:]


def parse_env_file(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if not path.exists():
        return data
    for raw in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'").strip('"')
        if key:
            data[key] = value
    return data


def parse_set_items(items: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for item in items:
        text = str(item or "").strip()
        if not text or "=" not in text:
            continue
        key, value = text.split("=", 1)
        key = key.strip()
        if key:
            out[key] = value
    return out


def write_env_file(path: Path, envs: dict[str, str]) -> None:
    lines = [
        "# Auto-generated by configure_runtime_env.py",
        f"# generated_at={now_iso()}",
    ]
    for key in sorted(envs):
        value = envs[key]
        lines.append(f"{key}={value}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8", newline="\n")
    try:
        os.chmod(path, 0o600)
    except Exception:
        pass


def main() -> int:
    home = Path(os.path.expanduser("~"))
    parser = argparse.ArgumentParser(description="Configure runtime env values")
    parser.add_argument("--env-file", default=str(home / ".openclaw/ops/runtime.env"))
    parser.add_argument("--set", dest="sets", action="append", default=[], help="KEY=VALUE, repeatable")
    parser.add_argument("--dingtalk-webhook-url", default="")
    parser.add_argument("--dingtalk-secret", default="")
    parser.add_argument("--emit-json", action="store_true")
    args = parser.parse_args()

    env_file = Path(args.env_file).expanduser()
    envs = parse_env_file(env_file)
    before = dict(envs)

    updates = parse_set_items(args.sets)
    if str(args.dingtalk_webhook_url).strip():
        updates["DINGTALK_WEBHOOK_URL"] = str(args.dingtalk_webhook_url).strip()
    if str(args.dingtalk_secret).strip():
        updates["DINGTALK_SECRET"] = str(args.dingtalk_secret).strip()

    if not updates:
        result = {
            "ok": False,
            "error": "no updates provided",
            "env_file": str(env_file),
        }
        print(json.dumps(result, ensure_ascii=False))
        return 2

    envs.update(updates)
    write_env_file(env_file, envs)

    changed: dict[str, dict[str, Any]] = {}
    for key, new_value in updates.items():
        old_value = before.get(key)
        changed[key] = {
            "changed": old_value != new_value,
            "old_masked": mask_value(old_value or ""),
            "new_masked": mask_value(new_value),
        }

    result = {
        "ok": True,
        "generated_at": now_iso(),
        "env_file": str(env_file),
        "updated_keys": sorted(updates.keys()),
        "changed": changed,
    }
    if args.emit_json:
        print(json.dumps(result, ensure_ascii=False))
    else:
        print(f"env_file={result['env_file']}")
        print(f"updated_keys={','.join(result['updated_keys'])}")
        for key in sorted(changed):
            item = changed[key]
            print(f"{key}=changed:{item['changed']},old:{item['old_masked']},new:{item['new_masked']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
